### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by SorenHolstHansen**

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Finally found some time to pull this down and give it a shot. Thanks again for starting this process @SorenHolstHansen - i really appreciate it.

In general, I like the overall style/vibe. I think its a totally reasonable extension of the minor "brand" work that's happened so far. I did run into a small bug - it seems like if I open up the contributing guide, my browser is stuck showing that screen. I can't seem to navigate to another view

**Comment by SorenHolstHansen** [comment]
No worries, glad to help!

**Comment by SorenHolstHansen** [comment]
I've put all of the readme in the docs now

**Comment by AlecAivazis** [comment]
Thanks for uploading the rest of the content - I'm still seeing some strange behavior when I try to navigate to a page that doesn't update. I'm having a hard time reproducing it consistently but I'll keep trying.

Thanks for being so patient! I am going to set aside some time this holiday break to get these docs out there so I really appreciate all the help

**Comment by SorenHolstHansen** [comment]
I think the issues are related to HMR and mdsvex, since I can only reproduce when I have made changes. Not too sure though

**Comment by AlecAivazis** [comment]
Ah, i think i figured out how to reproduce the issue - if i click on the houdini logo, the navigation stops working

**Comment by SorenHolstHansen** [comment]
I will try and look into it

**Comment by SorenHolstHansen** [comment]
I can fix it if i disable routing, I will see if I can find a better solution

**Comment by AlecAivazis** [comment]
Whoops, didn't realize force pushing onto the main branch would close this. I started to flesh out a landing page as well as organize the docs a little more so unfortunately a lot of this PR is no longer valid - sorry about that!  I appreciate the hard work. This PR gave me a lot of examples of things to do in the latest version. There is still a lot to be designed/written so stay tuned!

**Comment by SorenHolstHansen** [comment]
No worries, just happy to help

**Comment by AlecAivazis** [comment]
@SorenHolstHansen thought you might like to know the live version of the new doc site is available at www.houdinigraphql.com. Very curious to hear what you think. It's still missing search but I hope to get that implemented very soon.

**Comment by SorenHolstHansen** [comment]
Have only given it a quick skim, but i think it looks great!
I will give it a closer look when i get some time, in two weeks time

There were some small issues with the code samples on mobile, but otherwise it was great

**Comment by SorenHolstHansen** [comment]
Have had a better look at it now, and I think it looks very great, love to see Houdini progressing so well!

**Comment by AlecAivazis** [comment]
Thanks for the kind words!

**Pull request closed without merging**
